# BEGIN ANSIBLE MANAGED BLOCK

# to populate install_config
env_baseDomain: ocpz.wsclab.endicott.ibm.com
env_compute_arch: s390x #default to s390x
env_control_count: 3 #default 3
env_control_arch: s390x #default s390x
env_metadata_name: distribution
env_cidr: 10.128.0.0/14 #default 10.128.0.0/14 for now
env_host_prefix: 23 #default 23 for now
env_network_type: OpenShiftSDN #set default OpenShiftSDN
env_service_network: 172.30.0.0/16 #default 172.30.0.0/16
env_fips: "false" # "true" or "false" (include quotes)

env_pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfYzRjMGVlNDZmNmI0NDcyN2E5ZmZiZWVmMDgyNTYzNzg6VTgzMlYxSDdJMTBQM0cxVzNESkRWVlhXMVVTVjVUUjdVNjVGNzkwSldJVEEzSTcxOUlLTEJSWjI2MjVOQ0FDSg==","email":"jacob.emery@ibm.com"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfYzRjMGVlNDZmNmI0NDcyN2E5ZmZiZWVmMDgyNTYzNzg6VTgzMlYxSDdJMTBQM0cxVzNESkRWVlhXMVVTVjVUUjdVNjVGNzkwSldJVEEzSTcxOUlLTEJSWjI2MjVOQ0FDSg==","email":"jacob.emery@ibm.com"},"registry.connect.redhat.com":{"auth":"fHVoYy1wb29sLTMyMzRiMTdjLWIyOGQtNDYxMS1iNGE0LTc2MjAwY2YwYTNiYzpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSXhOREl5WmprM00yVXpZemMwTVRRek9UYzNNRGMzT0dNNE9XSTJNRGRqT1NKOS5WMW5sd1ptV1JueVJqTU9BLXRtR2dOVlJBQXk0VGs3RlVWazdmS2Nta2s2UVB3VFk0eWRNX2NNLXl5cWNZdGJUdjdLUkpNTjYyRG1yaThuc2QyY3Z4NU1xOWtKSnR1dHAyNjVEdDZZemxwNjctenEwWnZtcFJFUG82V3RrSWFyejlaUDB4X1ZWcGF6TS12aGVxTWpkUXNvMHZieXFZVGU5ZDIyTWUtTHVKSFJPWGY1c296NWdhQkw3UGVOelkyUGJpb3p5Zk5PZGhNb3ZIRlkwUXF6dmpXWHM2WUxMc21KeVo3amxmbDNhOHhKWnJkT0NNRUFXQzg2N3ljc01xWGNVVnNUSUZBRHdHTHNUSFJ0cG0wakFMdDNYZVpfNEJRQnp0UFVtMksxQVMyRE0zN2pJbGplVjBWelV0N2E1XzVrcjVOTmlQc0R0VGlOWmRXX1ZKREtWc0FVQ2hUY2JFT1RYUGtmTGpZR05aQmJ6dGVYLUlMWWIwc2dncEZqX3BzMDU1SUpwQ2NDWnB4dXZPZEk5Y01ZajdRbFl2TzV2c0RxQUZ2dXVUdGhPMzQ2SzNRUHdQLXNxUmFqU2NoOEVSSTZSaFZKaE53eVRPMGx0ellvRjZrMU0yUHhjX3VFZzFPVm1QSWxmZTNuWnFJUmczcExOM3cybnBqYXlkMnJxc2N2WU85NXRsbkFOa3B4YjJnVjVyYXZ5STBwMmx3VjZha2VXTGN4MlU1dGZWRHgzWW44VmtwdFlOeFUwQ016d2RWeWN6RlV6aFc2eUlvNmtMR09DQ3ExSVZGcVFKd191TjlWYVZlWjZHajVBcGlvc20wTllJd1QtVGFHbjNRUlB1bVBuSElIZlJGUUYzSF95SjhyUnNSRFJualpZT0ZvWmstQkNjTmdpOW1nb04yQQ==","email":"jacob.emery@ibm.com"},"registry.redhat.io":{"auth":"fHVoYy1wb29sLTMyMzRiMTdjLWIyOGQtNDYxMS1iNGE0LTc2MjAwY2YwYTNiYzpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSXhOREl5WmprM00yVXpZemMwTVRRek9UYzNNRGMzT0dNNE9XSTJNRGRqT1NKOS5WMW5sd1ptV1JueVJqTU9BLXRtR2dOVlJBQXk0VGs3RlVWazdmS2Nta2s2UVB3VFk0eWRNX2NNLXl5cWNZdGJUdjdLUkpNTjYyRG1yaThuc2QyY3Z4NU1xOWtKSnR1dHAyNjVEdDZZemxwNjctenEwWnZtcFJFUG82V3RrSWFyejlaUDB4X1ZWcGF6TS12aGVxTWpkUXNvMHZieXFZVGU5ZDIyTWUtTHVKSFJPWGY1c296NWdhQkw3UGVOelkyUGJpb3p5Zk5PZGhNb3ZIRlkwUXF6dmpXWHM2WUxMc21KeVo3amxmbDNhOHhKWnJkT0NNRUFXQzg2N3ljc01xWGNVVnNUSUZBRHdHTHNUSFJ0cG0wakFMdDNYZVpfNEJRQnp0UFVtMksxQVMyRE0zN2pJbGplVjBWelV0N2E1XzVrcjVOTmlQc0R0VGlOWmRXX1ZKREtWc0FVQ2hUY2JFT1RYUGtmTGpZR05aQmJ6dGVYLUlMWWIwc2dncEZqX3BzMDU1SUpwQ2NDWnB4dXZPZEk5Y01ZajdRbFl2TzV2c0RxQUZ2dXVUdGhPMzQ2SzNRUHdQLXNxUmFqU2NoOEVSSTZSaFZKaE53eVRPMGx0ellvRjZrMU0yUHhjX3VFZzFPVm1QSWxmZTNuWnFJUmczcExOM3cybnBqYXlkMnJxc2N2WU85NXRsbkFOa3B4YjJnVjVyYXZ5STBwMmx3VjZha2VXTGN4MlU1dGZWRHgzWW44VmtwdFlOeFUwQ016d2RWeWN6RlV6aFc2eUlvNmtMR09DQ3ExSVZGcVFKd191TjlWYVZlWjZHajVBcGlvc20wTllJd1QtVGFHbjNRUlB1bVBuSElIZlJGUUYzSF95SjhyUnNSRFJualpZT0ZvWmstQkNjTmdpOW1nb04yQQ==","email":"jacob.emery@ibm.com"}}}' #paste it into these single quotes here



# to fill inventory
env_ip_kvm_host: 9.60.87.132
env_ip_bastion: 9.60.87.139
env_ip_bootstrap: 9.60.87.133
env_ip_control_0: 9.60.87.136
env_ip_control_1: 9.60.87.137
env_ip_control_2: 9.60.87.138
env_ip_compute_0: 9.60.87.134
env_ip_compute_1: 9.60.87.135

# ssh
env_ssh_username: jacob #Username to use for ssh into kvm and bastion for first-time set-up of ansible passwordless ssh. Assumes same for both kvm and bastion.
env_ssh_pass: ibmzrocks #Password to use for ssh into kvm and bastion for first-time set-up of ansible passwordless ssh. Assumes same for both kvm and bastion.

# Ansible passwordless ssh
env_ssh_ans_name: ansible #Ansible ssh key pair filename. default=ansible
env_ssh_ans_pass: "" #Preferred Ansible ssh password. Recommended no password. default=""(no password)

# OpenShift cluster's ssh key comment
env_ssh_ocp_comm: "ocpz_distribution"

# networking
dns_nameserver: 9.60.87.139
default_gateway: 9.60.86.1
netmask: 255.255.254.0
# END ANSIBLE MANAGED BLOCK
