---

<<<<<<< HEAD
- hosts: kvm_host
=======
- hosts: kvm_hosts
>>>>>>> 600d4e0610d13ddb6a7d652ff4a2aef7775f61e6
  become: true
  tasks: 

  - name: update repository index
    yum:
      update_cache: yes

  - name: Ensure pre-requisite packages are installed
    yum:
      name:
        - libvirt
        - libvirt-devel
        - libvirt-daemon-kvm
        - qemu-kvm
        - virt-manager
        - libvirt-daemon-config-network
        - libvirt-client
        - qemu-img
      state: latest
      update_cache: yes

  - name: Ensure libvirtd is started
<<<<<<< HEAD
    script: ~/files/shell_scripts/start_libvirtd.sh
=======
    ansible.builtin.script: ~/files/shell_scripts/start_libvirtd.sh
>>>>>>> 600d4e0610d13ddb6a7d652ff4a2aef7775f61e6

  - name: create macvtap xml file
    file:
      path: "~/files/macvtap.xml"
      state: touch

  - name: Fill contents of macvtap xml file
    copy:
      dest: "~/files/macvtap.xml"
      content: |
        <network>
          <name>macvtap-net</name>
          <forward dev='enc1' mode='bridge'>
          <interface dev='enc1'/>
        </forward>
    
  - name: Set up macvtap bridge
    script: ~/files/shell_scripts/macvtap-net.sh 
